apiVersion: v1
kind: Service
metadata:
  namespace: test-service
  labels:
    app: test-service
  name: test-service
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: test-service
  type: ClusterIP
